### ISSUE TITLE
Not working after upgrading to Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by eErbLiddle** [platformio/platformio-atom-ide-terminal#905]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

Termianl now blank after upgrading to Ubuntu 20.04.1 LTS

### Steps to reproduce

1. Terminal Blank
2. No Functionality inside terminal its like a useless textbox
3.

**Expected behavior:** 
Termianl to pop up

**Actual behavior:** 
More like empty textbox

**Reproduces how often:** 
100%

### Versions

```
> atom --version
1.41.0
```
```
> apm --version

```
OS name and version: Ubuntu 20.04.1 LTS
Platformio-ide-terminal version: 2.10.0

**Comment by o02112** [comment]
Me too:

- Ubuntu 20.04.1 LTS
- Atom 1.52.0
- platformio-atom-ide-terminal 2.10.0

The terminal tab is blank without a _**Command prompt**_  like _"name@local:~$"_ something like that to place a command. Only have a block shaped "cursor" blinking in the left top of the terminal tab. 
The buttons(like "hide", "fullscreen", "close" etc.) are works ok.

I tried _**terminal-plus**_ package and it also has the same problem.

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.

**Comment by eErbLiddle** [comment]
I updated and am still having the issue. All I see is a blinking white square in the top left corner.

**Comment by Carlos-Develops** [comment]
Same Here:

- Atom 1.58.0

- cat /etc/os-release:
  - NAME="Ubuntu"
  - VERSION="20.04.3 LTS (Focal Fossa)"
  - ID=ubuntu
  - ID_LIKE=debian
  - PRETTY_NAME="Ubuntu 20.04.3 LTS"
  - VERSION_ID="20.04"
  - HOME_URL="https://www.ubuntu.com/"
  - SUPPORT_URL="https://help.ubuntu.com/"
  - BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  - PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  - VERSION_CODENAME=focal
  - UBUNTU_CODENAME=focal

- uname -a:
  - Linux pc 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
